require: rubocop-rspec

Layout/AlignHash:
  Enabled: false
LineLength:
  Enabled: false
Documentation:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
GuardClause:
  Enabled: false
PerlBackrefs:
  Enabled: false
CyclomaticComplexity:
  Max: 25
PerceivedComplexity:
  Max: 25
AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Max: 150
IndentArray:
  Enabled: false
RequireParentheses:
  Enabled: false
IfInsideElse:
  Enabled: false
IdenticalConditionalBranches:
  Enabled: false
NonLocalExitFromIterator:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
MultilineOperationIndentation:
  Enabled: false
IndentHeredoc:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
ParameterLists:
  Max: 6
RSpec:
  Enabled: false
Capybara/CurrentPathExpectation:
  Enabled: false
FactoryBot/CreateList:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'autotest/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
