version: "3"

services:

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - pbm-psql:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pbm-psql:
