<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "-f Cucumber::Formatter::Fuubar features" : "-f Cucumber::Formatter::Fuubar #{rerun}"
std_opts = "-f Cucumber::Formatter::Fuubar  --strict --tags ~@wip"
%>
default: <%= std_opts %> features
wip: --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
