development:
  adapter: postgresql
  host: localhost
  database: pbm_dev
  encoding: utf8
  timeout: 5000

test: &test
  adapter: postgresql
  host: localhost
  database: pbm_test
  encoding: utf8
  timeout: 5000
  min_messages: WARNING

production:
  adapter: postgresql
  database: pbm
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
