# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e6b82a44f83357b37c208845bd67165e51f00f25563215ad2a800314d4a26396da504271e80c4b782ad7a8e21de6cb8e121085b6f8202fc4cdc18c27cc7d2a3

test:
  secret_key_base: 32e86c5eb2dd78fc1ce6b738640459aaa6098d576f6b9a12b60efbf5b34ecb6ea27d7a2d1563728b43246a8279d8401a3596d92fb28935e483c330c3447c6635

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
